### ISSUE TITLE
API requests return error code 500 when submitting JSON files

### ISSUE THREAD

**Issue by E3245** [Big-Omega-3444/Resturant-Mangement#36]
I've been having issues with trying to POST or PUT a JSON file to the server from Javascript. I convert the JSON object into proper JSON before sending it to the server, but I get an Error 500 when trying to do this. I've had to use FormData objects, which the APIs accept.

How to reproduce:
1) Open a request to any of the API endpoints (either POST or PUT)
2) Send JSON object to API

Flask gives me this error when I try to send a JSON file to the server:

> [2020-04-09 08:00:23,485] ERROR in app: Exception on /api/inventory/5e8ea717d733c0457eabedfc [PUT]

**Comment by TheJohnLong** [comment]
don't include the "_id" field in the json
