### ISSUE TITLE
Leaving image blank in Menu category creation error

### ISSUE THREAD

**Issue by TheJohnLong** [Big-Omega-3444/Resturant-Mangement#64]
Add new menu category and leave image blank
best guess you're submitting an empty string
![image](https://user-images.githubusercontent.com/5272660/79167030-1b0e7280-7dac-11ea-8e46-885a0dd8950d.png)

**Comment by E3245** [comment]
The API doesn't like it if you POST or PUT a form or JSON data with an empty string for the URL

**Comment by TheJohnLong** [comment]
It checks to see if it's a valid URL. If the box is empty submit either nothing or a null value for that string
