### ISSUE TITLE
Changing ingredient quantities throws 404 error

### ISSUE THREAD

**Issue by CRaiden23** [Big-Omega-3444/Resturant-Mangement#67]
create an ingredient,
edit its quantity,
get "Error 404: obj "the ingredient's ID" doesn't exist!"

NOTE: what I thought was an ingredient ID was found to be a menu ID

**Comment by E3245** [comment]
Odd, I can't seem to reproduce this bug. I tried adding 5 new ingredients and editing their quantities and saved. I got no 404 errors with missing ingredients.

**Comment by CRaiden23** [comment]
I cleared out all of my ingredients and made new ones. Maybe the IDs lead somewhere else. Will Update

**Comment by CRaiden23** [comment]
Just looked for the ID it was saying didn't exist. It is an ID for a menu. Error was thrown at management.js:545:14

**Comment by E3245** [comment]
This was fixed with Commit 831cb547242cbc861386fac96fc4435b987f6960

**Comment by CRaiden23** [comment]
I'll try a rebase, see what happens
