### ISSUE TITLE
Cannot set multiple menu items to the same menu

### ISSUE THREAD

**Issue by CRaiden23** [Big-Omega-3444/Resturant-Mangement#68]
Create menus,
create menu items,
assign menu items to same menus using dropdown list,
only one menu item was assigned to that menu

**Comment by E3245** [comment]
This was fixed recently. I changed the dropdown to checkboxes instead. 
![image](https://user-images.githubusercontent.com/43194785/79181213-89b1f700-7dd1-11ea-8c60-8f153d4a51d6.png)

**Comment by CRaiden23** [comment]
Fixed with a rebase
